### ISSUE TITLE
RAML 1.0 Support

### ISSUE THREAD

**Issue by jcenturion** [n4ch03/atom-raml#11]
Do you have plans for supporting RAML 1.0?

**Comment by deem0n** [comment]
I am also interested.

**Comment by Narkhip** [comment]
Me too.

**Comment by dmartinezg** [comment]
:+1:

**Comment by nachoesmite** [comment]
I'll take a look if has sense to support [RAML 1.0](http://docs.raml.org/specs/1.0/) given the release of [API Workbench](http://apiworkbench.com/)
