### ISSUE TITLE
Dialogs cannot be refocused (clicks go through)

### ISSUE THREAD

**Issue by p4t5h3** [n4ch03/atom-raml#12]
Having Atom 1.1.0 and api-workbench 0.8.6 on OS X El Capitan I create a new file called `Photos.raml`. The outline and detail panes pop up on the right side. Following the ["Getting Started" in the documentation](http://apiworkbench.com/docs/) I right-click on the empty editor pane and create a new API via context menu. Entering the API title, version and base URI I would like to uncheck "Create sample resource" but the click focuses the underlying text editing area instead. From there on I can click everywhere in the dialog without effect. It seems impossible to focus. However I can manually trigger a click on the "Ok" button via Atom developer tools.

**Comment by nachoesmite** [comment]
@alomvar this issue should go to API Workbench Project right?

**Comment by p4t5h3** [comment]
Oh, yes! I do not know how I managed to get this here by accident. :smile:

Moved it here: https://github.com/mulesoft/api-workbench/issues/66

**Comment by p4t5h3** [comment]
See https://github.com/mulesoft/api-workbench/issues/66 for further information.
